name: base
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - aiofiles=22.1.0
    - alembic=1.14.0
    - anyio=4.6.2
    - apscheduler=3.10.4
    - blas=1.0=openblas
    - fastapi=0.112.2
    - geoalchemy2=0.15.2
    - geojson=3.1.0
    - numpy=1.26.4
    - openssl=3.3.2
    - packaging=24.1
    - pandas=2.2.2
    - pip=24.2
    - psycopg2=2.9.9
    - pydantic=2.8.2
    - python=3.12.2
    - python-dotenv=1.0.1
    - requests=2.32.3
    - setuptools=75.1.0
    - shapely=2.0.6
    - six=1.16.0
    - sqlalchemy=2.0.36
    - sqlmodel=0.0.22
    - starlette=0.38.2
    - typing-extensions=4.11.0
    - tzdata=2024b
    - tzlocal=5.2
    - urllib3=2.2.3
    - uvicorn=0.20.0
    - websockets=13.1
    - wheel=0.44.0
    - zipp=3.20.2
    - pip:
          - dnspython==2.7.0
          - email-validator==2.2.0
          - fastapi-cli==0.0.5
          - gtfs-realtime-bindings==1.0.0
          - httpcore==1.0.6
          - httptools==0.6.4
          - httpx==0.27.2
          - jinja2==3.1.4
          - markdown-it-py==3.0.0
          - markupsafe==3.0.2
          - mdurl==0.1.2
          - protobuf==5.28.3
          - pygments==2.18.0
          - pyperclip==1.9.0
          - python-multipart==0.0.12
          - pyyaml==6.0.2
          - rich==13.9.3
          - shellingham==1.5.4
          - typer==0.12.5
          - uvloop==0.21.0
          - watchfiles==0.24.0
