name: base
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - aiofiles=22.1.0
    - alembic=1.14.0
    - annotated-types
    - anyio=4.6.2
    - apscheduler=3.10.4
    - blas=1.0=openblas
    - bottleneck=1.3.7
    - brotli-python=1.0.9
    - bzip2=1.0.8
    - ca-certificates=2024.9.24
    - certifi=2024.8.30
    - charset-normalizer=3.3.2
    - click=8.1.7
    - expat=2.6.3
    - fastapi=0.112.2
    - geoalchemy2=0.15.2
    - geojson=3.1.0
    - geos=3.13.0
    - greenlet=3.0.1
    - h11=0.14.0
    - idna=3.7
    - importlib-metadata=7.0.1
    - importlib_resources=6.4.0
    - krb5=1.20.1
    - libcxx=19.1.3
    - libedit=3.1.20230828
    - libexpat=2.6.3
    - libffi=3.4.4
    - libgfortran=5.0.0
    - libgfortran5=11.3.0
    - libopenblas=0.3.21
    - libpq=12.17
    - libsqlite=3.45.2
    - libzlib=1.3.1
    - llvm-openmp=14.0.6
    - mako=1.2.3
    - ncurses=6.4
    - numexpr=2.10.1
    - numpy=1.26.4
    - numpy-base=1.26.4
    - openssl=3.3.2
    - packaging=24.1
    - pandas=2.2.2
    - pip=24.2
    - psycopg2=2.9.9
    - pydantic=2.8.2
    - pydantic-core=2.20.1
    - pysocks=1.7.1
    - python=3.12.2
    - python-dateutil=2.9.0post0
    - python-dotenv=1.0.1
    - python-tzdata=2023.3
    - python_abi=3.12
    - pytz=2024.1
    - readline=8.2
    - requests=2.32.3
    - setuptools=75.1.0
    - shapely=2.0.6
    - six=1.16.0
    - sniffio=1.3.0
    - sqlalchemy=2.0.36
    - sqlite=3.45.2
    - sqlmodel=0.0.22
    - starlette=0.38.2
    - tk=8.6.13
    - typing-extensions=4.11.0
    - typing_extensions=4.11.0
    - tzdata=2024b
    - tzlocal=5.2
    - urllib3=2.2.3
    - uvicorn=0.20.0
    - websockets=13.1
    - wheel=0.44.0
    - xz=5.4.6
    - zipp=3.20.2
    - zlib=1.3.1
    - pip:
          - dnspython==2.7.0
          - email-validator==2.2.0
          - fastapi-cli==0.0.5
          - gtfs-realtime-bindings==1.0.0
          - httpcore==1.0.6
          - httptools==0.6.4
          - httpx==0.27.2
          - jinja2==3.1.4
          - markdown-it-py==3.0.0
          - markupsafe==3.0.2
          - mdurl==0.1.2
          - protobuf==5.28.3
          - pygments==2.18.0
          - pyperclip==1.9.0
          - python-multipart==0.0.12
          - pyyaml==6.0.2
          - rich==13.9.3
          - shellingham==1.5.4
          - typer==0.12.5
          - uvloop==0.21.0
          - watchfiles==0.24.0
