"""srid_4326

Revision ID: bc2968bcbb5a
Revises: a8d52d2f6519
Create Date: 2024-11-05 01:24:14.377941

"""
from typing import Sequence, Union
import geoalchemy2

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2968bcbb5a'
down_revision: Union[str, None] = 'a8d52d2f6519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gtfs_shapes', 'line',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=28992, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.alter_column('gtfs_stops', 'location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=28992, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gtfs_stops', 'location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=28992, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    op.alter_column('gtfs_shapes', 'line',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=28992, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    # ### end Alembic commands ###
