from models.realtime.stop_time_event import StopTimeEventBase
from models.realtime.stop_time_update import StopTimeUpdateBase
from models.realtime.trip_update import TripUpdateBase
from models.realtime.vehicle_position import VehiclePositionBase
